# default_language_version:
#   python: python3.8

repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.5.0
    hooks:
      - id: trailing-whitespace # trims trailing whitespace.
      - id: check-yaml # checks yaml files for parsable syntax.
      - id: check-toml # checks toml files for parsable syntax.
      - id: check-json # checks json files for parsable syntax.
      - id: end-of-file-fixer # ensures that a file is either empty, or ends with one newline
      # - id: check-docstring-first
      - id: check-case-conflict # checks for files that would conflict in case-insensitive filesystems
      - id: check-merge-conflict # checks for files that contain merge conflict strings
      - id: detect-private-key # detects the presence of private keys
      - id: check-executables-have-shebangs # ensures that (non-binary) executables have a shebang.
      - id: check-shebang-scripts-are-executable
      - id: debug-statements # checks for debugger imports and py37+ `breakpoint()` calls in python source

  - repo: https://github.com/asottile/pyupgrade
    rev: v3.15.0
    hooks:
      - id: pyupgrade
        args: [--py39-plus]

  - repo: https://github.com/snok/pep585-upgrade
    rev: v1.0
    hooks:
      - id: upgrade-type-hints

  - repo: https://github.com/asottile/add-trailing-comma
    rev: v3.1.0
    hooks:
      - id: add-trailing-comma
        args: [--py36-plus]

  - repo: https://github.com/PyCQA/isort
    rev: 5.12.0
    hooks:
      - id: isort
        args: [--settings-path, ./pyproject.toml]

  - repo: https://github.com/myint/docformatter
    rev: v1.7.5
    hooks:
      - id: docformatter
        args: [--in-place, --wrap-summaries=115, --wrap-descriptions=120]

  - repo: https://github.com/psf/black
    rev: 23.11.0
    hooks:
      - id: black
        name: Format code

  - repo: https://github.com/asottile/blacken-docs
    rev: 1.16.0
    hooks:
      - id: blacken-docs
        # additional_dependencies: [black==...]  # if you want to fix a version of black

  - repo: https://github.com/asottile/yesqa
    rev: v1.5.0
    hooks:
      - id: yesqa
        # additional_dependencies: [flake8==...]  # if you want to fix a version of flake8

  - repo: https://github.com/executablebooks/mdformat
    rev: 0.7.17
    hooks:
      - id: mdformat
        additional_dependencies:
          - mdformat-gfm
          #- mdformat-black
          - mdformat_frontmatter
        exclude: |
          (?x)^(
              CHANGELOG.md
          )$

  - repo: https://github.com/PyCQA/flake8
    rev: 6.1.0
    hooks:
      - id: flake8
        name: Check PEP8
        args: [--exit-zero] # don't block pre-commit
        verbose: true
